services:
  # Frontend as a Node web_service serving static files
  - type: web_service
    name: supplier-frontend
    env: node
    root: formfrontend        
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l $PORT
    branch: main
    autoDeploy: true

  # Backend (Express)
  - type: web_service
    name: supplier-backend
    env: node
    root: BACKEND
    buildCommand: npm install
    startCommand: node index.js
    branch: main
    autoDeploy: true

  # ML backend (Flask)
  - type: web_service
    name: supplier-ml
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    branch: main
    autoDeploy: true
