services:
  - type: web_service
    name: supplier-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    branch: main
    autoDeploy: true

  - type: web_service
    name: supplier-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    branch: main
    autoDeploy: true

  - type: web_service
    name: supplier-ml
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    branch: main
    autoDeploy: true
